export { default as getBackgroundColor } from './src/get-background-color'
export { default as getColor } from './src/get-color'
export { default as solidColorWithHierarchy } from './src/solid-color-with-hierarchy'
export { default as spacing } from './src/spacing'
export { default as typography } from './src/typography'
export { default as inputElement } from './src/input-element'
export * from './src/types'
